# Generated by Django 3.1.7 on 2021-03-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit_habitlog_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
            preserve_default=False,
        ),
    ]
