# Generated by Django 3.1.7 on 2021-03-18 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210317_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='core.profile'),
            preserve_default=False,
        ),
    ]
