# Generated by Django 3.1.7 on 2021-03-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210319_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='log',
        ),
        migrations.AddField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.habit'),
        ),
    ]
