# Generated by Django 3.1.7 on 2021-03-19 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210319_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 20, 19, 19, 571911, tzinfo=utc), unique=True),
        ),
    ]
