# Generated by Django 3.1.7 on 2021-03-19 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210319_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 20, 41, 1, 263174, tzinfo=utc), unique=True),
        ),
    ]
