# Generated by Django 3.1.7 on 2021-03-19 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210319_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 22, 20, 40, 199772, tzinfo=utc)),
        ),
    ]
