# Generated by Django 3.1.7 on 2021-03-19 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210319_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 22, 24, 58, 61952, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('date', 'habit'), name='unique datelog'),
        ),
    ]
