# Generated by Django 3.1.7 on 2021-03-20 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210319_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 1, 24, 2, 424283, tzinfo=utc)),
        ),
    ]
