# Generated by Django 3.1.7 on 2021-03-20 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210320_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 3, 56, 10, 449984, tzinfo=utc)),
        ),
    ]
