# Generated by Django 3.1.7 on 2021-03-20 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210320_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
