# Generated by Django 3.1.7 on 2021-03-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210317_1944'),
        ('core', '0014_auto_20210320_0358'),
    ]

    operations = [
    ]
