# Generated by Django 3.1.7 on 2021-03-22 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20210322_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='log',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='author',
            field=models.ForeignKey(default='me', on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(default='idk something', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('date', 'habit'), name='unique datelog'),
        ),
    ]
